# Generated by Django 3.2.7 on 2021-09-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepermission',
            name='name',
        ),
    ]
