# Generated by Django 3.2.7 on 2021-09-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderpermission',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='folder_manager.folder'),
        ),
    ]
